export { default as StarBackground } from './StarBackground';
export { default as LandingNavbar } from './LandingNavbar';
export { default as HeroSection } from './HeroSection';
export { default as FeaturesSection } from './FeaturesSection';
export { default as HowItWorksSection } from './HowItWorksSection';
export { default as ServicesSection } from './ServicesSection';
export { default as TestimonialsSection } from './TestimonialsSection';
export { default as FAQSection } from './FAQSection';
export { default as LandingFooter } from './LandingFooter';
